// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Comment struct {
	ID        string `json:"id"`
	UserID    int    `json:"user_id"`
	RepliedID int    `json:"replied_id"`
	Content   string `json:"content"`
	PostDate  string `json:"post_date"`
}

type LikeOrDislike struct {
	UserID      int    `json:"user_id"`
	TargetID    int    `json:"target_id"`
	TargetType  string `json:"target_type"`
	Actions     string `json:"actions"`
	PerformedAt string `json:"performed_at"`
}

type Playlist struct {
	ID          string `json:"id"`
	UserID      int    `json:"user_id"`
	Name        string `json:"name"`
	URL         string `json:"url"`
	Type        string `json:"type"`
	Description string `json:"description"`
	CreatedAt   string `json:"created_at"`
	LastUpdated string `json:"last_updated"`
	TotalViews  int    `json:"total_views"`
}

type PlaylistContent struct {
	PlaylistID string `json:"playlist_id"`
	VideoID    string `json:"video_id"`
	AddedDate  string `json:"added_date"`
}

type Popular struct {
	ID        string `json:"id"`
	Category  string `json:"category"`
	Types     string `json:"types"`
	StartDate string `json:"start_date"`
}

type PopularContent struct {
	PopularID string `json:"popular_id"`
	VideoID   string `json:"video_id"`
}

type Session struct {
	ID          string `json:"id"`
	IP          string `json:"ip"`
	Location    string `json:"location"`
	Type        string `json:"type"`
	Restriction bool   `json:"restriction"`
}

type SessionQueue struct {
	SessionID string `json:"session_id"`
	VideoID   string `json:"video_id"`
}

type Subscriptions struct {
	ID             string `json:"id"`
	UserID         int    `json:"user_id"`
	SubscribedID   int    `json:"subscribed_id"`
	SubscribedDate string `json:"subscribed_date"`
	Notification   bool   `json:"notification"`
}

type UploadQueue struct {
	ID         string `json:"id"`
	VideoID    int    `json:"video_id"`
	UploadDate string `json:"upload_date"`
}

type User struct {
	ID                string `json:"id"`
	Name              string `json:"name"`
	Picture           string `json:"picture"`
	MembershipStatus  string `json:"membership_status"`
	BillingType       string `json:"billing_type"`
	MembershipExpDate string `json:"membership_exp_date"`
	JoinDate          string `json:"join_date"`
	Email             string `json:"email"`
}

type Video struct {
	ID           string `json:"id"`
	Videos       string `json:"videos"`
	Title        string `json:"title"`
	Descriptions string `json:"descriptions"`
	UploaderID   int    `json:"uploader_id"`
	Label        string `json:"label"`
	Privacy      string `json:"privacy"`
	Type         string `json:"type"`
	Thumbnail    string `json:"thumbnail"`
	UploadDate   string `json:"upload_date"`
	Location     string `json:"location"`
	ViewCount    int    `json:"view_count"`
	Category     string `json:"category"`
}

type VideoCategory struct {
	VideoID    string `json:"video_id"`
	CategoryID string `json:"category_id"`
}

type AddToPlaylist struct {
	ID     string `json:"id"`
	Videos string `json:"videos"`
}

type AddToQueue struct {
	SessionID string `json:"session_id"`
	Queue     string `json:"queue"`
}

type AddedVideo struct {
	Video     []*Video `json:"video"`
	AddedDate []string `json:"added_date"`
}

type ChangePicture struct {
	ID   int    `json:"id"`
	Pict string `json:"pict"`
}

type ChangeVideoDetail struct {
	ID           int    `json:"id"`
	Title        string `json:"title"`
	Descriptions string `json:"descriptions"`
}

type CreateNewSession struct {
	IP       string `json:"ip"`
	Location string `json:"location"`
	Type     string `json:"type"`
}

type DoLikeOrDislike struct {
	ID     int `json:"id"`
	UserID int `json:"user_id"`
}

type IncreaseView struct {
	ID int `json:"id"`
}

type NewComment struct {
	UserID  int    `json:"user_id"`
	Content string `json:"content"`
}

type NewMembership struct {
	ID          int    `json:"id"`
	BillingType string `json:"billing_type"`
}

type NewPlaylist struct {
	UserID      int    `json:"user_id"`
	Name        string `json:"name"`
	URL         string `json:"url"`
	Type        string `json:"type"`
	Description string `json:"description"`
}

type NewPopularList struct {
	Category  string `json:"category"`
	Types     string `json:"types"`
	StartDate string `json:"start_date"`
}

type NewPopularVideo struct {
	PopularID string `json:"popular_id"`
	VideoID   string `json:"video_id"`
}

type NewReply struct {
	UserID    int    `json:"user_id"`
	RepliedID int    `json:"replied_id"`
	Content   string `json:"content"`
}

type NewSubscription struct {
	UserID       int `json:"user_id"`
	SubscribedID int `json:"subscribed_id"`
}

type NewUploadQueue struct {
	VideoID    int    `json:"video_id"`
	UploadDate string `json:"upload_date"`
}

type NewUser struct {
	Name    string `json:"name"`
	Email   string `json:"email"`
	Picture string `json:"picture"`
}

type NewVideo struct {
	Video        string `json:"video"`
	Title        string `json:"title"`
	Descriptions string `json:"descriptions"`
	Label        string `json:"label"`
	Privacy      string `json:"privacy"`
	UploaderID   int    `json:"uploader_id"`
	Type         string `json:"type"`
	Thumbnail    string `json:"thumbnail"`
	Location     string `json:"location"`
	Category     string `json:"category"`
}

type NewVideoCategory struct {
	VideoID    string `json:"video_id"`
	CategoryID string `json:"category_id"`
}

type PlaylistVideoDetail struct {
	Playlist *Playlist   `json:"playlist"`
	Videos   *AddedVideo `json:"videos"`
}

type PopularVideoDetail struct {
	Popular *Popular `json:"popular"`
	Videos  []*Video `json:"videos"`
}

type QueueVideoDetail struct {
	Session *Session `json:"session"`
	Videos  []*Video `json:"videos"`
}

type UserSubscriptionDetail struct {
	User          *User            `json:"user"`
	Subscriptions []*Subscriptions `json:"subscriptions"`
}

type UserVideoDetail struct {
	User   *User    `json:"user"`
	Videos []*Video `json:"videos"`
}

type VideoDetail struct {
	Video        *Video `json:"video"`
	User         *User  `json:"user"`
	LikeCount    int    `json:"likeCount"`
	DislikeCount int    `json:"dislikeCount"`
}
